// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTig-ZDfWrp0fCpfjgavaI8tqrUfiHIj8',
    appId: '1:151565412475:web:aae450e77b8c6fd9d15ade',
    messagingSenderId: '151565412475',
    projectId: 'canca-8f5de',
    authDomain: 'canca-8f5de.firebaseapp.com',
    storageBucket: 'canca-8f5de.firebasestorage.app',
    measurementId: 'G-DS4HYC57P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEHastZyAyi7Okuy1dUb4HKACYDjxNyU',
    appId: '1:151565412475:android:72cd37a8126a2937d15ade',
    messagingSenderId: '151565412475',
    projectId: 'canca-8f5de',
    storageBucket: 'canca-8f5de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASE8kC8JwqW-G5x6yWXX-XDoveBMpZgPY',
    appId: '1:151565412475:ios:874da83e73f8cbf4d15ade',
    messagingSenderId: '151565412475',
    projectId: 'canca-8f5de',
    storageBucket: 'canca-8f5de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASE8kC8JwqW-G5x6yWXX-XDoveBMpZgPY',
    appId: '1:151565412475:ios:874da83e73f8cbf4d15ade',
    messagingSenderId: '151565412475',
    projectId: 'canca-8f5de',
    storageBucket: 'canca-8f5de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTig-ZDfWrp0fCpfjgavaI8tqrUfiHIj8',
    appId: '1:151565412475:web:1fed58507243e83dd15ade',
    messagingSenderId: '151565412475',
    projectId: 'canca-8f5de',
    authDomain: 'canca-8f5de.firebaseapp.com',
    storageBucket: 'canca-8f5de.firebasestorage.app',
    measurementId: 'G-TSYR7Q8Z55',
  );

}